"""Generate multi-platform demonstration dataset for SentimentScope AI."""

from __future__ import annotations

import csv
from pathlib import Path


RECORDS = [
    {
        "post_id": "demo_1001",
        "platform": "Twitter",
        "timestamp": "2026-08-01 09:15:00",
        "author": "@tech_enthusiast",
        "text": "The battery life on my new iPhone 16 is outstanding! Easily lasts all day.",
        "brand": "Apple",
        "product": "iPhone 16",
        "topic": "Battery",
        "sentiment": "positive",
        "sentiment_score": 0.88,
        "engagement_metrics": '{"likes": 142, "retweets": 18}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1002",
        "platform": "Twitter",
        "timestamp": "2026-08-01 10:20:00",
        "author": "@flyer_dan",
        "text": "Smooth boarding and friendly crew on Delta flight DL102 today.",
        "brand": "Delta",
        "product": "Flight DL102",
        "topic": "Customer Service",
        "sentiment": "positive",
        "sentiment_score": 0.82,
        "engagement_metrics": '{"likes": 34, "retweets": 2}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1003",
        "platform": "Reddit",
        "timestamp": "2026-08-01 11:05:00",
        "author": "u/gadget_geek",
        "text": "Review after 2 weeks: Samsung Galaxy S25 display is breathtaking in bright sunlight.",
        "brand": "Samsung",
        "product": "Galaxy S25",
        "topic": "Display",
        "sentiment": "positive",
        "sentiment_score": 0.91,
        "engagement_metrics": '{"upvotes": 285, "comments": 42}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1004",
        "platform": "Reddit",
        "timestamp": "2026-08-01 12:30:00",
        "author": "u/prime_buyer",
        "text": "Amazon delivery arrived 2 hours ahead of schedule. Truly impressed.",
        "brand": "Amazon",
        "product": "Prime Delivery",
        "topic": "Delivery",
        "sentiment": "positive",
        "sentiment_score": 0.85,
        "engagement_metrics": '{"upvotes": 67, "comments": 8}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1005",
        "platform": "Instagram",
        "timestamp": "2026-08-01 14:10:00",
        "author": "creator_sarah",
        "text": "Unboxing the titanium Apple Watch Ultra 3. The build quality feels premium.",
        "brand": "Apple",
        "product": "Apple Watch",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.89,
        "engagement_metrics": '{"likes": 1240, "comments": 88}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1006",
        "platform": "YouTube",
        "timestamp": "2026-08-01 15:45:00",
        "author": "TechPulseDaily",
        "text": "Testing Samsung Galaxy AI live translation in Tokyo. It actually works seamlessly!",
        "brand": "Samsung",
        "product": "Galaxy AI",
        "topic": "Software",
        "sentiment": "positive",
        "sentiment_score": 0.84,
        "engagement_metrics": '{"likes": 3400, "comments": 210}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1007",
        "platform": "Twitter",
        "timestamp": "2026-08-01 16:30:00",
        "author": "@commuter_jane",
        "text": "Delta in-flight WiFi was stable enough for video calls throughout the flight.",
        "brand": "Delta",
        "product": "In-Flight WiFi",
        "topic": "Connectivity",
        "sentiment": "positive",
        "sentiment_score": 0.76,
        "engagement_metrics": '{"likes": 19, "retweets": 1}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1008",
        "platform": "Twitter",
        "timestamp": "2026-08-01 17:15:00",
        "author": "@alex_b",
        "text": "Ordered school supplies from Amazon yesterday and they just arrived.",
        "brand": "Amazon",
        "product": "Prime",
        "topic": "Delivery",
        "sentiment": "neutral",
        "sentiment_score": 0.05,
        "engagement_metrics": '{"likes": 5, "retweets": 0}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1009",
        "platform": "Reddit",
        "timestamp": "2026-08-01 18:00:00",
        "author": "u/audio_phile",
        "text": "Comparing Apple AirPods Pro 3 vs Galaxy Buds 3 Pro for active noise cancellation.",
        "brand": "Apple",
        "product": "AirPods Pro",
        "topic": "Hardware",
        "sentiment": "neutral",
        "sentiment_score": 0.02,
        "engagement_metrics": '{"upvotes": 112, "comments": 56}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1010",
        "platform": "Instagram",
        "timestamp": "2026-08-01 19:25:00",
        "author": "travel_with_leo",
        "text": "Sunset view from 35000 feet aboard Delta A350.",
        "brand": "Delta",
        "product": "Delta A350",
        "topic": "Travel",
        "sentiment": "positive",
        "sentiment_score": 0.92,
        "engagement_metrics": '{"likes": 890, "comments": 24}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1011",
        "platform": "YouTube",
        "timestamp": "2026-08-01 20:50:00",
        "author": "GadgetUnfiltered",
        "text": "Galaxy S25 battery drain test: 7 hours screen-on time under heavy gaming.",
        "brand": "Samsung",
        "product": "Galaxy S25",
        "topic": "Battery",
        "sentiment": "neutral",
        "sentiment_score": 0.10,
        "engagement_metrics": '{"likes": 850, "comments": 95}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1012",
        "platform": "Twitter",
        "timestamp": "2026-08-01 22:10:00",
        "author": "@cloud_dev",
        "text": "Setting up my AWS Lambda instances with Amazon Bedrock API.",
        "brand": "Amazon",
        "product": "AWS",
        "topic": "Cloud",
        "sentiment": "neutral",
        "sentiment_score": 0.0,
        "engagement_metrics": '{"likes": 12, "retweets": 3}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1013",
        "platform": "Twitter",
        "timestamp": "2026-08-02 08:30:00",
        "author": "@morning_coffee",
        "text": "Apple iOS 19 developer beta dropped this morning. Installing now.",
        "brand": "Apple",
        "product": "iOS",
        "topic": "Software",
        "sentiment": "neutral",
        "sentiment_score": 0.0,
        "engagement_metrics": '{"likes": 42, "retweets": 4}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1014",
        "platform": "Twitter",
        "timestamp": "2026-08-02 09:45:00",
        "author": "@frequent_flyer",
        "text": "Minor 15-min weather delay with Delta in Atlanta, but gate agents handled it calmly.",
        "brand": "Delta",
        "product": "Flight DL402",
        "topic": "Delay",
        "sentiment": "neutral",
        "sentiment_score": -0.10,
        "engagement_metrics": '{"likes": 8, "retweets": 0}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1015",
        "platform": "Reddit",
        "timestamp": "2026-08-02 11:15:00",
        "author": "u/tech_curious",
        "text": "Does anyone else feel the Samsung trade-in valuation is lower this year?",
        "brand": "Samsung",
        "product": "Trade-In",
        "topic": "Pricing",
        "sentiment": "negative",
        "sentiment_score": -0.45,
        "engagement_metrics": '{"upvotes": 94, "comments": 38}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1016",
        "platform": "Reddit",
        "timestamp": "2026-08-02 13:00:00",
        "author": "u/shopper_99",
        "text": "Amazon package left in the rain without plastic wrapping. Damaged box.",
        "brand": "Amazon",
        "product": "Prime Delivery",
        "topic": "Delivery",
        "sentiment": "negative",
        "sentiment_score": -0.62,
        "engagement_metrics": '{"upvotes": 145, "comments": 29}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1017",
        "platform": "Instagram",
        "timestamp": "2026-08-02 14:30:00",
        "author": "lifestyle_vlogger",
        "text": "Morning workout tracked on Apple Watch Series 10. Heart rate sensor is spot on.",
        "brand": "Apple",
        "product": "Apple Watch",
        "topic": "Fitness",
        "sentiment": "positive",
        "sentiment_score": 0.85,
        "engagement_metrics": '{"likes": 612, "comments": 18}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1018",
        "platform": "YouTube",
        "timestamp": "2026-08-02 16:00:00",
        "author": "MobileWorldReviews",
        "text": "Samsung OneUI 7 long-term review: smoother animations and customizable widgets.",
        "brand": "Samsung",
        "product": "OneUI 7",
        "topic": "Software",
        "sentiment": "positive",
        "sentiment_score": 0.79,
        "engagement_metrics": '{"likes": 2100, "comments": 140}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1019",
        "platform": "Twitter",
        "timestamp": "2026-08-02 17:40:00",
        "author": "@flyer_mike",
        "text": "Quick luggage return from Delta at MSP airport. Bag was on belt in 10 mins.",
        "brand": "Delta",
        "product": "Baggage",
        "topic": "Service",
        "sentiment": "positive",
        "sentiment_score": 0.81,
        "engagement_metrics": '{"likes": 15, "retweets": 0}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1020",
        "platform": "Twitter",
        "timestamp": "2026-08-02 19:10:00",
        "author": "@alex_deals",
        "text": "Amazon Kindle Paperwhite is on discount for Prime members today.",
        "brand": "Amazon",
        "product": "Kindle",
        "topic": "Pricing",
        "sentiment": "positive",
        "sentiment_score": 0.70,
        "engagement_metrics": '{"likes": 55, "retweets": 8}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1021",
        "platform": "Reddit",
        "timestamp": "2026-08-02 20:30:00",
        "author": "u/code_ninja",
        "text": "Apple M4 MacBook Pro compilation benchmarks blow my old workstation away.",
        "brand": "Apple",
        "product": "MacBook Pro",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.94,
        "engagement_metrics": '{"upvotes": 420, "comments": 75}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1022",
        "platform": "Instagram",
        "timestamp": "2026-08-02 21:45:00",
        "author": "foodie_traveler",
        "text": "Tasty pre-ordered meal on Delta first class flight to Seattle.",
        "brand": "Delta",
        "product": "In-Flight Dining",
        "topic": "Food",
        "sentiment": "positive",
        "sentiment_score": 0.83,
        "engagement_metrics": '{"likes": 430, "comments": 12}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1023",
        "platform": "YouTube",
        "timestamp": "2026-08-02 22:30:00",
        "author": "ElectroScope",
        "text": "Amazon Echo Show 12 full setup and smart home ecosystem walkthrough.",
        "brand": "Amazon",
        "product": "Echo Show",
        "topic": "Smart Home",
        "sentiment": "neutral",
        "sentiment_score": 0.12,
        "engagement_metrics": '{"likes": 980, "comments": 64}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1024",
        "platform": "Twitter",
        "timestamp": "2026-08-03 08:15:00",
        "author": "@dev_sam",
        "text": "Apple Xcode update finally fixed the swift compiler caching issue.",
        "brand": "Apple",
        "product": "Xcode",
        "topic": "Developer",
        "sentiment": "positive",
        "sentiment_score": 0.78,
        "engagement_metrics": '{"likes": 89, "retweets": 11}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1025",
        "platform": "Twitter",
        "timestamp": "2026-08-03 09:50:00",
        "author": "@biz_traveler",
        "text": "Delta Sky Club at JFK Terminal 4 was crowded but coffee was fresh.",
        "brand": "Delta",
        "product": "Sky Club",
        "topic": "Lounge",
        "sentiment": "neutral",
        "sentiment_score": 0.15,
        "engagement_metrics": '{"likes": 22, "retweets": 1}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1026",
        "platform": "Reddit",
        "timestamp": "2026-08-03 11:20:00",
        "author": "u/phone_fanatic",
        "text": "Samsung Galaxy Z Fold 7 hinge feels much more durable than predecessor.",
        "brand": "Samsung",
        "product": "Galaxy Z Fold",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.87,
        "engagement_metrics": '{"upvotes": 310, "comments": 49}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1027",
        "platform": "Reddit",
        "timestamp": "2026-08-03 13:40:00",
        "author": "u/digital_buyer",
        "text": "Customer service from Amazon refund team was fast and painless.",
        "brand": "Amazon",
        "product": "Customer Service",
        "topic": "Support",
        "sentiment": "positive",
        "sentiment_score": 0.80,
        "engagement_metrics": '{"upvotes": 88, "comments": 7}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1028",
        "platform": "Instagram",
        "timestamp": "2026-08-03 15:10:00",
        "author": "photo_journey",
        "text": "Captured this macro shot using Samsung Galaxy S25 Ultra 200MP sensor.",
        "brand": "Samsung",
        "product": "Galaxy S25 Ultra",
        "topic": "Camera",
        "sentiment": "positive",
        "sentiment_score": 0.93,
        "engagement_metrics": '{"likes": 1540, "comments": 62}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1029",
        "platform": "YouTube",
        "timestamp": "2026-08-03 16:45:00",
        "author": "AirTravelInsider",
        "text": "Is Delta Premium Select worth the extra cost? Transatlantic review.",
        "brand": "Delta",
        "product": "Premium Select",
        "topic": "Seating",
        "sentiment": "neutral",
        "sentiment_score": 0.20,
        "engagement_metrics": '{"likes": 1750, "comments": 180}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1030",
        "platform": "Twitter",
        "timestamp": "2026-08-03 18:20:00",
        "author": "@music_fan",
        "text": "Spatial Audio on Apple Music with AirPods Max is truly immersive.",
        "brand": "Apple",
        "product": "AirPods Max",
        "topic": "Audio",
        "sentiment": "positive",
        "sentiment_score": 0.90,
        "engagement_metrics": '{"likes": 64, "retweets": 5}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1031",
        "platform": "Twitter",
        "timestamp": "2026-08-03 20:00:00",
        "author": "@smart_home_pro",
        "text": "Amazon Alexa routine triggered my morning blinds and coffee machine.",
        "brand": "Amazon",
        "product": "Alexa",
        "topic": "Smart Home",
        "sentiment": "positive",
        "sentiment_score": 0.75,
        "engagement_metrics": '{"likes": 31, "retweets": 2}',
        "provenance": "Synthetic Demo",
    },
    # --- Spike Period for Delta (Outage & Severe Cancellations) ---
    {
        "post_id": "demo_1032",
        "platform": "Twitter",
        "timestamp": "2026-08-04 07:10:00",
        "author": "@traveler_tom",
        "text": "What is going on with Delta today? Flight DL809 cancelled with zero explanation!",
        "brand": "Delta",
        "product": "Flight DL809",
        "topic": "Cancellation",
        "sentiment": "negative",
        "sentiment_score": -0.88,
        "engagement_metrics": '{"likes": 410, "retweets": 85}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1033",
        "platform": "Twitter",
        "timestamp": "2026-08-04 07:45:00",
        "author": "@angry_flyer",
        "text": "STUCK IN ATLANTA! Delta systems are completely down and lines are 300 people long #DeltaOutage",
        "brand": "Delta",
        "product": "Delta IT",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.95,
        "engagement_metrics": '{"likes": 1250, "retweets": 340}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1034",
        "platform": "Reddit",
        "timestamp": "2026-08-04 08:15:00",
        "author": "u/delta_stranded",
        "text": "Megathread: Nationwide Delta outage. Ground stop declared, customer service phone disconnecting.",
        "brand": "Delta",
        "product": "Delta Network",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.92,
        "engagement_metrics": '{"upvotes": 2400, "comments": 680}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1035",
        "platform": "Twitter",
        "timestamp": "2026-08-04 08:50:00",
        "author": "@jessica_m",
        "text": "Missed my wedding anniversary because Delta cancelled every connecting flight out of DTW. Unacceptable!",
        "brand": "Delta",
        "product": "Flight DL304",
        "topic": "Cancellation",
        "sentiment": "negative",
        "sentiment_score": -0.97,
        "engagement_metrics": '{"likes": 890, "retweets": 190}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1036",
        "platform": "Twitter",
        "timestamp": "2026-08-04 09:20:00",
        "author": "@corp_exec",
        "text": "Our entire executive team stranded in Chicago thanks to Delta IT meltdown.",
        "brand": "Delta",
        "product": "Delta IT",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.91,
        "engagement_metrics": '{"likes": 520, "retweets": 98}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1037",
        "platform": "Reddit",
        "timestamp": "2026-08-04 09:55:00",
        "author": "u/airport_sleep",
        "text": "Sitting on the tarmac for 4 hours with no AC and no water on Delta DL1104. Lawsuit incoming.",
        "brand": "Delta",
        "product": "Flight DL1104",
        "topic": "Customer Service",
        "sentiment": "negative",
        "sentiment_score": -0.98,
        "engagement_metrics": '{"upvotes": 3100, "comments": 490}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1038",
        "platform": "YouTube",
        "timestamp": "2026-08-04 10:30:00",
        "author": "AviationCrisisNews",
        "text": "Breaking: Major Delta Air Lines computer outage grounds hundreds of flights worldwide.",
        "brand": "Delta",
        "product": "Delta Fleet",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.85,
        "engagement_metrics": '{"likes": 8900, "comments": 1240}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1039",
        "platform": "Instagram",
        "timestamp": "2026-08-04 11:10:00",
        "author": "stranded_in_atl",
        "text": "Current nightmare at Atlanta airport. Thousands of bags piled up outside baggage claim.",
        "brand": "Delta",
        "product": "Baggage",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.93,
        "engagement_metrics": '{"likes": 4200, "comments": 380}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1040",
        "platform": "Twitter",
        "timestamp": "2026-08-04 11:45:00",
        "author": "@family_vacay",
        "text": "Family vacation ruined by Delta cancellations. Customer care hold time is 8 hours!",
        "brand": "Delta",
        "product": "Customer Service",
        "topic": "Support",
        "sentiment": "negative",
        "sentiment_score": -0.94,
        "engagement_metrics": '{"likes": 670, "retweets": 130}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1041",
        "platform": "Twitter",
        "timestamp": "2026-08-04 12:30:00",
        "author": "@tech_watcher",
        "text": "Meanwhile Apple Vision Pro 2 rumors heating up with micro-OLED displays.",
        "brand": "Apple",
        "product": "Vision Pro",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.72,
        "engagement_metrics": '{"likes": 115, "retweets": 14}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1042",
        "platform": "Reddit",
        "timestamp": "2026-08-04 13:10:00",
        "author": "u/delta_pilot_anon",
        "text": "Throwaway account: dispatch server cascade failure behind today Delta ground stop.",
        "brand": "Delta",
        "product": "Dispatch",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.89,
        "engagement_metrics": '{"upvotes": 4500, "comments": 810}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1043",
        "platform": "Twitter",
        "timestamp": "2026-08-04 14:00:00",
        "author": "@consumer_advocate",
        "text": "Delta needs to issue immediate full refunds and hotel vouchers to all stranded passengers.",
        "brand": "Delta",
        "product": "Refunds",
        "topic": "Policy",
        "sentiment": "negative",
        "sentiment_score": -0.86,
        "engagement_metrics": '{"likes": 1400, "retweets": 420}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1044",
        "platform": "YouTube",
        "timestamp": "2026-08-04 14:45:00",
        "author": "TechReviewHub",
        "text": "Samsung Galaxy Tab S10 Ultra vs iPad Pro M4: Which tablet reigns supreme?",
        "brand": "Samsung",
        "product": "Galaxy Tab S10",
        "topic": "Comparison",
        "sentiment": "neutral",
        "sentiment_score": 0.10,
        "engagement_metrics": '{"likes": 2300, "comments": 165}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1045",
        "platform": "Twitter",
        "timestamp": "2026-08-04 15:30:00",
        "author": "@flyer_rob",
        "text": "Day 1 of the Delta meltdown and still no bag, no hotel, no assistance at Boston Logan.",
        "brand": "Delta",
        "product": "Baggage",
        "topic": "Support",
        "sentiment": "negative",
        "sentiment_score": -0.96,
        "engagement_metrics": '{"likes": 780, "retweets": 115}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1046",
        "platform": "Instagram",
        "timestamp": "2026-08-04 16:15:00",
        "author": "wanderlust_claire",
        "text": "Sleeping on the floor at JFK because Delta cancelled my flight to London.",
        "brand": "Delta",
        "product": "Flight DL001",
        "topic": "Cancellation",
        "sentiment": "negative",
        "sentiment_score": -0.95,
        "engagement_metrics": '{"likes": 2100, "comments": 190}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1047",
        "platform": "Twitter",
        "timestamp": "2026-08-04 17:00:00",
        "author": "@ecommerce_guy",
        "text": "Amazon logistics delivery fleet seems unaffected by the severe storms.",
        "brand": "Amazon",
        "product": "Amazon Logistics",
        "topic": "Delivery",
        "sentiment": "positive",
        "sentiment_score": 0.80,
        "engagement_metrics": '{"likes": 44, "retweets": 3}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1048",
        "platform": "Reddit",
        "timestamp": "2026-08-04 18:30:00",
        "author": "u/gadget_repair",
        "text": "How easy is it to replace the battery in Apple iPhone 16? Full teardown guide.",
        "brand": "Apple",
        "product": "iPhone 16",
        "topic": "Repairability",
        "sentiment": "neutral",
        "sentiment_score": 0.05,
        "engagement_metrics": '{"upvotes": 210, "comments": 34}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1049",
        "platform": "Twitter",
        "timestamp": "2026-08-04 19:40:00",
        "author": "@angry_dan",
        "text": "Delta management should answer for this historic operational collapse. Absolute disaster.",
        "brand": "Delta",
        "product": "Leadership",
        "topic": "Outage",
        "sentiment": "negative",
        "sentiment_score": -0.98,
        "engagement_metrics": '{"likes": 2200, "retweets": 610}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1050",
        "platform": "Twitter",
        "timestamp": "2026-08-04 21:00:00",
        "author": "@night_owl_flyer",
        "text": "Still waiting in rebooking queue at Minneapolis since 10am Delta. Horrible communication.",
        "brand": "Delta",
        "product": "Customer Service",
        "topic": "Support",
        "sentiment": "negative",
        "sentiment_score": -0.92,
        "engagement_metrics": '{"likes": 350, "retweets": 45}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1051",
        "platform": "Twitter",
        "timestamp": "2026-08-05 06:30:00",
        "author": "@morning_commuter",
        "text": "Delta delays carrying into Day 2. Over 1200 flights already grounded this morning.",
        "brand": "Delta",
        "product": "Delta Fleet",
        "topic": "Delays",
        "sentiment": "negative",
        "sentiment_score": -0.90,
        "engagement_metrics": '{"likes": 880, "retweets": 210}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1052",
        "platform": "Reddit",
        "timestamp": "2026-08-05 08:00:00",
        "author": "u/flyer_help",
        "text": "Advice on claiming EU261 compensation from Delta for yesterday cancelled flight?",
        "brand": "Delta",
        "product": "Compensation",
        "topic": "Customer Service",
        "sentiment": "negative",
        "sentiment_score": -0.60,
        "engagement_metrics": '{"upvotes": 540, "comments": 120}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1053",
        "platform": "Twitter",
        "timestamp": "2026-08-05 09:15:00",
        "author": "@tech_pulse",
        "text": "Apple announced new MagSafe charging accessories with 25W fast Qi2 support.",
        "brand": "Apple",
        "product": "MagSafe",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.81,
        "engagement_metrics": '{"likes": 320, "retweets": 28}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1054",
        "platform": "Twitter",
        "timestamp": "2026-08-05 10:45:00",
        "author": "@business_insider_fan",
        "text": "Samsung foundry reports improved yields for 3nm mobile chipsets.",
        "brand": "Samsung",
        "product": "Foundry",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.76,
        "engagement_metrics": '{"likes": 150, "retweets": 19}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1055",
        "platform": "Instagram",
        "timestamp": "2026-08-05 12:00:00",
        "author": "retail_therapy",
        "text": "Amazon doorstep package drop captured on my Ring doorbell.",
        "brand": "Amazon",
        "product": "Ring",
        "topic": "Smart Home",
        "sentiment": "neutral",
        "sentiment_score": 0.08,
        "engagement_metrics": '{"likes": 190, "comments": 9}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1056",
        "platform": "Twitter",
        "timestamp": "2026-08-05 13:30:00",
        "author": "@flyer_sarah",
        "text": "Delta app finally allowed me to request a refund instead of rebooking. Sad to cancel the trip.",
        "brand": "Delta",
        "product": "App",
        "topic": "Refund",
        "sentiment": "negative",
        "sentiment_score": -0.72,
        "engagement_metrics": '{"likes": 180, "retweets": 12}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1057",
        "platform": "YouTube",
        "timestamp": "2026-08-05 15:00:00",
        "author": "EverydayAviation",
        "text": "How Delta is recovering from the IT crash: Crew repositioning explained.",
        "brand": "Delta",
        "product": "Operations",
        "topic": "Operations",
        "sentiment": "neutral",
        "sentiment_score": -0.10,
        "engagement_metrics": '{"likes": 3400, "comments": 290}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1058",
        "platform": "Twitter",
        "timestamp": "2026-08-05 16:40:00",
        "author": "@sammy_fan",
        "text": "Samsung Galaxy Watch Ultra battery lasts 3 days with GPS tracking enabled. Best smartwatch for Android.",
        "brand": "Samsung",
        "product": "Galaxy Watch",
        "topic": "Battery",
        "sentiment": "positive",
        "sentiment_score": 0.92,
        "engagement_metrics": '{"likes": 210, "retweets": 15}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1059",
        "platform": "Reddit",
        "timestamp": "2026-08-05 18:20:00",
        "author": "u/prime_shopper",
        "text": "Amazon Prime video library expansion this month looks really good.",
        "brand": "Amazon",
        "product": "Prime Video",
        "topic": "Entertainment",
        "sentiment": "positive",
        "sentiment_score": 0.78,
        "engagement_metrics": '{"upvotes": 320, "comments": 45}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1060",
        "platform": "Twitter",
        "timestamp": "2026-08-05 20:10:00",
        "author": "@apple_coder",
        "text": "Swift 6 concurrency model is so much cleaner once you understand actors.",
        "brand": "Apple",
        "product": "Swift",
        "topic": "Software",
        "sentiment": "positive",
        "sentiment_score": 0.84,
        "engagement_metrics": '{"likes": 195, "retweets": 22}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1061",
        "platform": "Twitter",
        "timestamp": "2026-08-06 08:00:00",
        "author": "@frequent_flyer",
        "text": "Delta operations slowly returning to normal. Boarding flight DL550 on time this morning.",
        "brand": "Delta",
        "product": "Flight DL550",
        "topic": "Operations",
        "sentiment": "positive",
        "sentiment_score": 0.70,
        "engagement_metrics": '{"likes": 85, "retweets": 6}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1062",
        "platform": "Reddit",
        "timestamp": "2026-08-06 10:15:00",
        "author": "u/phone_critic",
        "text": "Samsung Galaxy S25 software update patch notes: camera shutter lag significantly reduced.",
        "brand": "Samsung",
        "product": "Galaxy S25",
        "topic": "Camera",
        "sentiment": "positive",
        "sentiment_score": 0.86,
        "engagement_metrics": '{"upvotes": 410, "comments": 58}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1063",
        "platform": "Instagram",
        "timestamp": "2026-08-06 12:30:00",
        "author": "aesthetic_desk",
        "text": "Clean desk setup with Apple Studio Display and Mac mini.",
        "brand": "Apple",
        "product": "Studio Display",
        "topic": "Hardware",
        "sentiment": "positive",
        "sentiment_score": 0.91,
        "engagement_metrics": '{"likes": 1890, "comments": 44}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1064",
        "platform": "Twitter",
        "timestamp": "2026-08-06 14:45:00",
        "author": "@prime_user",
        "text": "Amazon Prime same-day delivery order arrived within 4 hours. Incredible speed.",
        "brand": "Amazon",
        "product": "Prime Delivery",
        "topic": "Delivery",
        "sentiment": "positive",
        "sentiment_score": 0.95,
        "engagement_metrics": '{"likes": 120, "retweets": 8}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1065",
        "platform": "YouTube",
        "timestamp": "2026-08-06 16:20:00",
        "author": "AeroReview",
        "text": "Delta customer compensation guide: What you are entitled to after cancellations.",
        "brand": "Delta",
        "product": "Compensation",
        "topic": "Policy",
        "sentiment": "neutral",
        "sentiment_score": 0.05,
        "engagement_metrics": '{"likes": 4200, "comments": 380}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1066",
        "platform": "Twitter",
        "timestamp": "2026-08-06 18:00:00",
        "author": "@gadget_girl",
        "text": "Samsung Galaxy Buds 3 Pro sound signature is punchy with deep bass.",
        "brand": "Samsung",
        "product": "Galaxy Buds 3 Pro",
        "topic": "Audio",
        "sentiment": "positive",
        "sentiment_score": 0.87,
        "engagement_metrics": '{"likes": 95, "retweets": 4}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1067",
        "platform": "Reddit",
        "timestamp": "2026-08-06 20:10:00",
        "author": "u/apple_user",
        "text": "The new Siri conversational mode with Apple Intelligence is actually helpful for summaries.",
        "brand": "Apple",
        "product": "Apple Intelligence",
        "topic": "AI",
        "sentiment": "positive",
        "sentiment_score": 0.83,
        "engagement_metrics": '{"upvotes": 275, "comments": 61}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1068",
        "platform": "Twitter",
        "timestamp": "2026-08-07 09:00:00",
        "author": "@business_travel",
        "text": "Full Delta flight schedule restored today. Kudos to the gate agents who worked overtime.",
        "brand": "Delta",
        "product": "Operations",
        "topic": "Customer Service",
        "sentiment": "positive",
        "sentiment_score": 0.79,
        "engagement_metrics": '{"likes": 210, "retweets": 18}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1069",
        "platform": "Instagram",
        "timestamp": "2026-08-07 11:30:00",
        "author": "urban_photog",
        "text": "Street photography through the lens of Samsung Galaxy S25 Ultra 5x optical telephoto.",
        "brand": "Samsung",
        "product": "Galaxy S25 Ultra",
        "topic": "Camera",
        "sentiment": "positive",
        "sentiment_score": 0.94,
        "engagement_metrics": '{"likes": 2450, "comments": 89}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1070",
        "platform": "YouTube",
        "timestamp": "2026-08-07 14:00:00",
        "author": "TechTomorrow",
        "text": "Amazon Project Kuiper satellite broadband field test: Speed tests vs Starlink.",
        "brand": "Amazon",
        "product": "Project Kuiper",
        "topic": "Broadband",
        "sentiment": "neutral",
        "sentiment_score": 0.15,
        "engagement_metrics": '{"likes": 5600, "comments": 490}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1071",
        "platform": "Twitter",
        "timestamp": "2026-08-07 16:15:00",
        "author": "@ios_dev",
        "text": "Apple developer documentation for CoreML has gotten much clearer this year.",
        "brand": "Apple",
        "product": "CoreML",
        "topic": "Developer",
        "sentiment": "positive",
        "sentiment_score": 0.80,
        "engagement_metrics": '{"likes": 130, "retweets": 14}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1072",
        "platform": "Reddit",
        "timestamp": "2026-08-07 18:45:00",
        "author": "u/delta_frequent",
        "text": "Received a $200 flight credit and 25000 SkyMiles from Delta for the delay. Fair apology.",
        "brand": "Delta",
        "product": "SkyMiles",
        "topic": "Customer Service",
        "sentiment": "positive",
        "sentiment_score": 0.75,
        "engagement_metrics": '{"upvotes": 380, "comments": 64}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1073",
        "platform": "Twitter",
        "timestamp": "2026-08-07 20:30:00",
        "author": "@smart_buyer",
        "text": "Amazon returns at Whole Foods drop-off counter are so fast and convenient.",
        "brand": "Amazon",
        "product": "Returns",
        "topic": "Customer Service",
        "sentiment": "positive",
        "sentiment_score": 0.88,
        "engagement_metrics": '{"likes": 72, "retweets": 5}',
        "provenance": "Synthetic Demo",
    },
    {
        "post_id": "demo_1074",
        "platform": "Instagram",
        "timestamp": "2026-08-07 22:00:00",
        "author": "night_vibes",
        "text": "Night mode shot with Apple iPhone 16 Pro Max. Minimal noise, great dynamic range.",
        "brand": "Apple",
        "product": "iPhone 16 Pro Max",
        "topic": "Camera",
        "sentiment": "positive",
        "sentiment_score": 0.92,
        "engagement_metrics": '{"likes": 1780, "comments": 52}',
        "provenance": "Synthetic Demo",
    },
]


def generate_dataset(output_path: Path | str) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "post_id",
        "platform",
        "timestamp",
        "author",
        "text",
        "brand",
        "product",
        "topic",
        "sentiment",
        "sentiment_score",
        "engagement_metrics",
        "provenance",
    ]

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        writer.writerows(RECORDS)

    print(f"Successfully generated {len(RECORDS)} records in {path}")


if __name__ == "__main__":
    dest = Path(__file__).resolve().parents[1] / "data" / "sample" / "multi_platform_demo.csv"
    generate_dataset(dest)
